### ISSUE TITLE
Update app? Cannot login

### ISSUE THREAD

**Issue by yajo** [YunoHost-Apps/mautrix_whatsapp_ynh#144] opened 2024-05-25 06:54 UTC
### Describe the bug

When telling the bot to ˋloginˋ, it answers: *Failed to log in: outdated client. The bridge must be updated to continue.*

### Context

- Hardware: *Raspberry Pi at home*
- YunoHost version: 11.2.12
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: *0.10.5~ynh1*

### Steps to reproduce

1. Talk to bot
2. Say ˋloginˋ
### Expected behavior
 It should print a QR code to scan with phone.
### Logs

https://paste.yunohost.org/metijiyozi

**Comment by thardev** [comment] 2024-05-26 14:43
Hi @yajo 

Could you try to update to the latest version of the package `v10.0.7` to see if that solves the issue? 🙂

**Comment by TiberiusRegenschein** [comment] 2024-05-29 19:45
Same issue here in a different setting but with already version v10.0.7

Context

    Hardware: NUC X86
    YunoHost version: 11.2.12
    I have access to my server: Through SSH | through the webadmin
    Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

- Installed version v10.0.7 successfully
- mautrix_whatsapp service is running and can also be restarted. The following error log is present:

- {"level":"info","name":"mautrix-whatsapp","version":"0.10.7","built_at":"Apr 16 2024, 11:14:51","go_version":"go1.22.2","time":"2024-05-29T21:30:39.431040518+02:00","message":"Initializing bridge"}
{"level":"info","time":"2024-05-29T21:30:39.432319916+02:00","message":"Bridge initialization complete, starting..."}
{"level":"info","db_section":"main","current_version":57,"oldest_compatible_version":45,"latest_known_version":57,"time":"2024-05-29T21:30:39.458818418+02:00","message":"Database is up to date"}
{"level":"info","db_section":"matrix_state","current_version":5,"oldest_compatible_version":5,"latest_known_version":5,"time":"2024-05-29T21:30:39.464353657+02:00","message":"Database is up to date"}
{"level":"info","address":"0.0.0.0:8450","time":"2024-05-29T21:30:39.464691526+02:00","message":"Starting HTTP listener"}
{"level":"warn","req_id":1,"body_parse_err":"failed to unmarshal response body: invalid character '<' looking for beginning of value","method":"GET","url":"https://myliberty.eu/_matrix/client/versions?user_id=%40whatsappbot%3Amyliberty.eu","duration":40.301262,"status_code":200,"response_length":-1,"response_mime":"text/html","time":"2024-05-29T21:30:39.504974963+02:00","message":"Request parsing failed"}
{"level":"error","error":"failed to unmarshal response body: invalid character '<' looking for beginning of value","time":"2024-05-29T21:30:39.505161807+02:00","message":"Failed to connect to homeserver, retrying in 10 seconds..."}

Steps to reproduce

Install Synapse 1.107.0~ynh1
Install mautrix-whatsapp  v10.0.7
Talk to bot
    Say ˋloginˋ

Expected behavior

It should print a QR code to scan with phone.
On the same server there is also a mautrix signal installation with the following [error](https://github.com/YunoHost-Apps/mautrix_signal_ynh/issues/101) This may or may not be related

Thanks for checking 😃

**Comment by yajo** [comment] 2024-05-31 15:52
My problem was fixed. The new problem you say seems related to a homeserver
host name change. Edit the config.yaml of your app and restart the service

**Comment by thardev** [comment] 2024-06-01 11:21
Hi @TiberiusRegenschein

I think @yajo is right, that kind of error you see in the logs is similar of what I saw when something in the `config.yaml` has the wrong configuration. Please check what @yajo suggested and close this if it is solved by that 🙂

**Comment by TiberiusRegenschein** [comment] 2024-06-02 19:18
@thardev Your advise was the right one.
I found out that due to Synapse in the meantime needed it's own subdomain and me opening one for it, the wrong domain, the main domain, was still listed in the `config.yaml`. After updating all works for me as expected. Thank you for your support 😃

**Closed as completed** 2024-06-06 06:02 UTC
